In [5]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [12]:
import numpy as np 
a = np.zeros(3)
b = np.arange(10)
print(a)
print(b)


[0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]


In [30]:
import numpy as np

a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b = np.array([[5,6,7,8,9],[5,6,7,8,9]])
print(sum(a,b))
c = np.concatenate((a,b),axis = 0)
print(c)

[[ 7 10 13 16 19]
 [ 7 10 13 16 19]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [5 6 7 8 9]
 [5 6 7 8 9]]


In [27]:
import numpy as np
a = np.array([1,2,3,40,5,6])
print(a.reshape(3,2))
print(a.max())

[[ 1  2]
 [ 3 40]
 [ 5  6]]
40


In [45]:
import numpy as np 
a = np.arange(2,21,2)
print(a*a)

[  4  16  36  64 100 144 196 256 324 400]


In [39]:
import numpy as np 
a = np.array([51,61,71,81,54,76,87,67,56,85,99,77,55,93,73])
print(a.max())
print(a.min())
print(np.std(a))
print(np.mean(a))

99
51
14.472042012100435
72.4


In [44]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(a.reshape(5,4))
a[a%2==0] = -1
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [60]:
import numpy as np 
a = np.linspace(1,25,num = 25,dtype=int)
a = a.reshape(5,5)
diagonals = a.diagonal()
print(a)
print()
print(diagonals)
print()
print(a.sum())
print()
print(a.sum(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 1  7 13 19 25]

325

[ 15  40  65  90 115]
